<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Etch.Gpu</RootNamespace>
    <AssemblyName>Etch.Gpu</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <NoWarn>$(NoWarn);CS1591;ET0105;CA1062;CA1815;CA1031;CA1720;CA1028;CA1008;CA1711</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Etch.Abstractions\Etch.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Etch.ClipBlendGradient\Etch.ClipBlendGradient.csproj" />
    <ProjectReference Include="..\..\src\Etch.Primitives\Etch.Primitives.csproj" />
    <ProjectReference Include="..\..\src\Etch.Shaders\Etch.Shaders.csproj" />
    <ProjectReference Include="..\Etch.Gpu.Native\Etch.Gpu.Native.csproj" />
    <ProjectReference Include="..\..\src-gen\Etch.Analyzers\Etch.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>