changelog:
  categories:
    - title: Breaking
      labels: [breaking]
    - title: Added
      labels: [enhancement, feature]
    - title: Changed
      labels: [changed, performance]
    - title: Fixed
      labels: [bug, fix]
    - title: Deprecated
      labels: [deprecated]
    - title: Known Issues
      labels: [known-issue]
  exclude:
    labels: [duplicate, wontfix, invalid, question, documentation]
