<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\Sourcegen.props" />
  <PropertyGroup>
    <RootNamespace>Etch.Analyzers</RootNamespace>
    <AssemblyName>Etch.Analyzers</AssemblyName>
    <NoWarn>$(NoWarn);CS1591;RS2008;RS1032;RS1008;RS1033;CA1307;CA1310;CA1866;CA1062;CS9210;RS1025</NoWarn>
  </PropertyGroup>
</Project>