using System;

namespace Etch;

/// <summary>
/// Minimal structured-logging sink for Etch hot paths. Consumers (e.g. CascadeUI) bridge
/// this to their platform logger (<c>ILogger</c>, <c>spdlog</c>, etc.) in one line.
/// </summary>
/// <remarks>
/// <para>
/// <b>Design constraints.</b> No scopes, no filters, no generics. The single
/// <see cref="Log"/> method accepts a <see cref="ReadOnlySpan{T}"/> of key/value pairs so
/// that generated call sites can use <c>stackalloc</c> and stay allocation-free on every
/// call. Consumers who need filtering do it in their bridge layer before calling
/// <see cref="Log"/>.
/// </para>
/// <para>
/// <b>Panic vs. logging.</b> <see cref="EtchLogLevel.Error"/> and above are still routed
/// through <see cref="Panic.Invariant"/> at the call site — <c>IEtchLogger</c> is for
/// operational diagnostics only, not exception-shaped failures.
/// </para>
/// </remarks>
public interface IEtchLogger
{
    /// <summary>Returns <see langword="true"/> if any message at <paramref name="level"/>
    /// would be emitted.</summary>
    bool IsEnabled(EtchLogLevel level);

    /// <summary>
    /// Emits a structured log event. The <paramref name="messageTemplate"/> is the message
    /// with named placeholders, e.g. <c>Tile {tileIndex} classified</c>. The
    /// <paramref name="args"/> span provides the argument values in matching index order.
    /// Callers generated by <c>EtchLoggerGenerator</c> use <c>stackalloc</c> to avoid
    /// heap allocation.
    /// </summary>
    /// <param name="level">Severity of the event.</param>
    /// <param name="eventId">Application-defined event identifier.</param>
    /// <param name="messageTemplate">Message template with named placeholders.</param>
    /// <param name="args">Argument values, one per placeholder in <paramref name="messageTemplate"/>.</param>
    void Log(EtchLogLevel level, int eventId, string messageTemplate, ReadOnlySpan<KeyValuePair<string, object?>> args);
}
