<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Etch.Gpu.Compositor</RootNamespace>
    <AssemblyName>Etch.Gpu.Compositor</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <NoWarn>$(NoWarn);CS1591;ET0105;CA1062;CA1815;CA1031;CA1720;CA1028;CA1008;CA1711</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Etch.Gpu\Etch.Gpu.csproj" />
    <ProjectReference Include="..\Etch.Tiling\Etch.Tiling.csproj" />
    <ProjectReference Include="..\..\src-gen\Etch.Analyzers\Etch.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Etch.Effects\Etch.Effects.csproj" />
  </ItemGroup>
</Project>