param(
    [string]$OutputPath = "./Etch.Abstractions.spdx.json"
)

$ErrorActionPreference = "Stop"

$published = Get-ChildItem -Recurse -Path . -Filter "Etch.Abstractions.dll" | Select-Object -First 1
if (-not $published) {
    Write-Host "No published DLL found"
    exit 1
}

$version = "2.3"
$timestamp = (Get-Date -Format "o")

$sbom = @{
    spdxVersion = "SPDX-$version"
    dataLicense = "CC0-1.0"
    SPDXID = "SPDXRef-Package"
    name = "Etch.Abstractions"
    downloadLocation = "NOASSERTION"
    licenseConcluded = "Apache-2.0"
    licenseDeclared = "Apache-2.0"
    creatorComment = "Generated by Etch CI"
    created = $timestamp
} | ConvertTo-Json -Depth 10

$sbom | Set-Content -Path $OutputPath -Encoding UTF8
Write-Host "SBOM written to $OutputPath"
