<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\build\Test.props" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Etch.Tests</RootNamespace>
    <AssemblyName>Etch.Abstractions.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Etch.Abstractions\Etch.Abstractions.csproj" />
  </ItemGroup>
</Project>
